name: Actions CI

on:
  push:
    branches: [ main ]
    paths: 
      - '**'
      - '!.editorconfig'
      - '!.gitattributes'
      - '!.gitignore'
      - '!*.md'
env:
  VERBOSITY: 'Minimal'
  CONFIGURATION: 'Release'
  DOTNET_NOLOGO: 'true'
  DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'

jobs: 
  Build:
    name: Build on .NET Core ${{ matrix.dotnet }}    
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        dotnet: ['8.0.204']
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract build and copyright information into variables
      id: info
      run: |
        echo "BUILD=$(date +'%Y%m%d')-${{ github.run_number }}" >> $GITHUB_ENV
        echo "##[set-output name=build;]$(echo $(git rev-list --count HEAD))"
        echo "##[set-output name=copyright;]$(echo © $(date -u +%Y) Bytewizer.  All rights reserved.)"
    
    - name: Show build information
      run: |
        echo build=${{ steps.info.outputs.build }}
        echo copyright=${{ steps.info.outputs.copyright }}
     
    - name: Setup .NET Core 
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet }}
      
    - name: Show .NET Core information
      run: dotnet --info
            
    - name: Build and pack runtime libraries project
      working-directory: src/  
      run: >- 
        dotnet pack -p:BuildNumber="${{ env.BUILD }}" -p:Copyright="${{ steps.info.outputs.copyright }}"
        --version-suffix prebuild.${{ steps.info.outputs.build }}
        --verbosity ${{ env.VERBOSITY }}
        --configuration ${{ env.CONFIGURATION }}
        --include-symbols

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build Packages ${{ env.BUILD }}
        path: "**/bin/${{ env.CONFIGURATION }}/**/*.nupkg"
